#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail


# run step 0 to step 5 by default
stage=0
stop_stage=0


. shared/parse_options.sh || exit 1

# vocab size for sentence piece models.
# It will generate data/lang_bpe_xxx,
# data/lang_bpe_yyy if the array contains xxx, yyy
vocab_sizes=(
  # 5000
  # 2000
  # 1000
  500
)

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh"

ssl_model=hubert-base
embedding_layer=9
ssl_dir=${ssl_model}_$embedding_layer

parts=(
    test-clean
    test-other
    dev-clean
    dev-other
    train-clean-100
    train-clean-360
    train-other-500
)

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Compute SSL features for librispeech"
  mkdir -p data/$ssl_dir
  if [ ! -e data/$ssl_dir/.librispeech.done ]; then
	  
    ./local/compute_ssl_librispeech.py --bpe-model  data/lang_bpe_500/bpe.model \
        --dataset "${parts[*]}" --model $ssl_model --layer $embedding_layer 
    
    touch data/$ssl_dir/.librispeech.done
  fi

  if [ ! -f data/$ssl_dir/librispeech_cuts_train-all-shuf.jsonl.gz ]; then
    if [ -f data/$ssl_dir/librispeech_cuts_train-other-500.jsonl.gz ]; then
    
      cat <(gunzip -c data/$ssl_dir/librispeech_cuts_train-clean-100.jsonl.gz) \
        <(gunzip -c data/$ssl_dir/librispeech_cuts_train-clean-360.jsonl.gz) \
        <(gunzip -c data/$ssl_dir/librispeech_cuts_train-other-500.jsonl.gz) | \
        shuf | gzip -c > data/$ssl_dir/librispeech_cuts_train-all-shuf.jsonl.gz

    else 
      cat <(gunzip -c data/$ssl_dir/librispeech_cuts_train-clean-100.jsonl.gz) \
        shuf | gzip -c > data/$ssl_dir/librispeech_cuts_train-all-shuf.jsonl.gz
    fi
  fi

  if [ ! -e data/$ssl_dir/.librispeech-validated.done ]; then
    log "Validating data/$ssl_dir for LibriSpeech"
    for part in ${parts[@]}; do
      python3 ./local/validate_manifest.py \
        data/$ssl_dir/librispeech_cuts_${part}.jsonl.gz
    done
    touch data/$ssl_dir/.librispeech-validated.done
  fi
fi

